# Travis CI config for cag-web

# Required env vars:
# - GITHUB_TOKEN: From the deployment repo's settings page

dist: xenial
language: minimal

before_install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

install:
- ./update-submodules.sh

script:
- hugo -v -s . -d build

deploy:
  provider: pages
  repo: CasualGaming/casualgaming.github.io
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  verbose: true
  local_dir: build
  on:
    branch: master
