# Travis CI config for cag-web

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (secure)
# - DOCKER_PASSWORD (secure)

dist: xenial
language: minimal

services:
  - docker

# Build Docker image
script:
- docker build -t "$DOCKER_REPO:latest" .

# Deploy to Ducker Hub
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
deploy:
  provider: script
  on:
    branch: master
    type: push
  skip_cleanup: true
  script: docker push "$DOCKER_REPO:latest"
