# Travis CI config for cag-web

# Required env vars:
# - GITHUB_TOKEN: From the deployment repo's settings page

dist: xenial
language: minimal

before_install:
- wget --quiet -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

script:
- hugo -v -s . -d build

deploy:
  provider: pages
  on:
    branch: master
    type: push
  repo: CasualGaming/casualgaming.github.io
  target_branch: master
  local_dir: build
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  verbose: true
