# Travis CI config for cag-web

# Required env vars:
# - GITHUB_TOKEN: From the deployment repo's settings page

dist: xenial
addons:
  apt:
    packages:
    - hugo

install:
- ./update-submodules.sh

script:
- hugo -v -s . -d build

deploy:
  provider: pages
  repo: CasualGaming/casualgaming.github.io
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  local_dir: build
  on:
    branch: master
