# Travis CI config for cag-web-2

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (secure)
# - DOCKER_PASSWORD (secure)

dist: bionic
language: minimal

services:
  - docker

jobs:
  include:
    - name: Build
      script: docker build -t "$DOCKER_REPO:latest" .

    - name: Deploy
      if: branch = master AND type = push
      install: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
      script: docker push "$DOCKER_REPO:latest"
