# Site settings
# Needs to be an absolute prefix
baseURL = "https://casualgaming.no/"
title = "Casual Gaming "
theme = "fifty"
enableEmoji = true
DefaultContentLanguage = "no"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-138227770-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Casual Gaming"
  description = "Datastreff og spillkvelder i Trondheim"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Image used when shared on social media
  # Unset to disable
  # All 4 must be provided if enabled
  # Can be overridden in pages
  sharingImage = "/img/logo-large.png"
  sharingImageType = "image/png"
  sharingImageWidth = "1000"
  sharingImageHeight = "1000"

  # 404 error customization
  [params.error404]
    heading = "Siden finnes ikke"
    text = "Vennligst [gå hjem](/)."

  # Navigation Section
  [params.navigation]
    logo = "logo-text.png"
    menu = "Meny"

    [[params.navigation.links]]
      name = "Hjem"
      url = "/"

    [[params.navigation.links]]
      name = "Om oss"
      url = "/om/"

    [[params.navigation.links]]
      name = "TrøndeLAN"
      url = "/trondelan/"

    [[params.navigation.links]]
      name = "StudLAN"
      url = "/studlan/"

    [[params.navigation.links]]
      name = "Spillkvelder"
      url = "/spillkvelder/"

    [[params.navigation.links]]
      name = "For samarbeidspartnere"
      url = "/for-samarbeidspartnere/"

    [[params.navigation.links]]
      name = "Opptak"
      url = "/opptak/"

  # Banner section
  [params.banner]
    bannerImage = "/img/home/banner.jpg"
    logoImage = "/img/logo-text.png"
    subtitle = "Datastreff og spillkvelder i Trondheim"

  # Tiles Section
  [params.tiles]
    enable = true

    [[params.tiles.showcase]]
      title = "TrøndeLAN"
      subtitle = "Trondheims største datatreff"
      image = "/img/home/trondelan.jpg"
      url = "/trondelan/"

    [[params.tiles.showcase]]
      title = "StudLAN"
      subtitle = "Et datatreff ved NTNU Gløshaugen"
      image = "/img/home/studlan.jpg"
      url = "/studlan/"

    [[params.tiles.showcase]]
      title = "Spillkvelder"
      subtitle = "Konsoll- og brettspillkvelder"
      image = "/img/home/konsoll_brett.jpg"
      url = "/spillkvelder/"

    [[params.tiles.showcase]]
      title = "Opptak"
      subtitle = "Bli med på arrangeringen"
      image = "/img/home/bli_med.png"
      constrainImage = true
      url = "/opptak/"

  # About section
  [params.about]
    enable = true
    title = "Casual Gaming"
    subtitle = """Casual Gaming er en ideell student- og ungdomsorganisasjon som har til formål
      å skape en felles sosial arena for spillinteresserte studenter og ungdom i Trondheimsområdet.
      **[Les mer om oss her.](/om)**"""

  # Partner section
  [params.partners]
    enable = true
    title = "Samarbeidspartnere"

    [[params.partners.partner]]
      image = "/img/partners/hyperion.png"
      alt = "Hyperion – Norsk Forbund for Fantastiske Fritidsinteresser"
      backgroundColor = ""
      url = "http://n4f.no/"
      description = "Vi er medlemsforening i Hyperion – Norsk Forbund for Fantastiske Fritidsinteresser"

#    [[params.partners.partner]]
#      image = "/img/partners/digitalkultur.png"
#      alt = "Norsk Digital Kultur"
#      backgroundColor = ""
#      url = "http://www.digitalkultur.no/"
#      description = "Vi er medlemsforening i Norsk Digital Kultur – Særforbundet for digital kultur i Hyperion"

    [[params.partners.partner]]
      image = "/img/partners/online.png"
      alt = "Online, linjeforeningen for informatikk ved NTNU"
      backgroundColor = ""
      url = "http://n4f.no/"
      description = "Vi har tilknytning til Online, linjeforeningen for informatikk ved NTNU"

    [[params.partners.partner]]
      image = "/img/partners/terrahost.png"
      alt = "Terrahost"
      backgroundColor = ""
      url = "https://terrahost.no/"
      description = "Terrahost støtter oss med en dedikert server for nettstedene våre"

#    [[params.partners.partner]]
#      image = "/img/logo.png"
#      alt = "AAAaaa"
#      url = "https://example.net/"
#      description = "Støtter oss med en dedikert server for nettstedene våre"

#    [[params.partners.partner]]
#      image = ""
#      alt = "BBBbbb"
#      url = "https://example.net/"
#      description = "Støtter oss med en dedikert server for nettstedene våre"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Casual Gaming"

    # "fas" means FontAwesome solid, "fab" means FA brands

    [[params.footer.social]]
      icon = "fab fa-facebook"
      url = "https://www.facebook.com/CasualGamingTrondheim/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fab fa-discord"
      url = "https://link.casualgaming.no/discord"
      label = "Discord"

    [[params.footer.social]]
      icon = "fab fa-twitch"
      url = "https://www.twitch.tv/casualgamingnorway"
      label = "Twitch"

    [[params.footer.social]]
      icon = "fab fa-youtube"
      #url = "https://www.youtube.com/channel/UCwE4Udkp8A881Dfvbfa6KLQ"
      url = "https://www.youtube.com/user/studlanNTNU/"
      label = "YouTube"

    [[params.footer.social]]
      icon = "fab fa-instagram"
      url = "https://www.instagram.com/casualgamingno"
      label = "Instagram"

    #[[params.footer.social]]
    #  icon = "fab fa-snapchat"
    #  url = "https://www.snapchat.com/add/casualgamingno"
    #  label = "Snapchat"

    [[params.footer.social]]
      icon = "fab fa-github"
      url = "https://www.github.com/CasualGaming"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fas fa-heartbeat"
      url = "https://status.casualgaming.no/"
      label = "Status"

    [[params.footer.social]]
      icon = "fas fa-life-ring"
      url = "mailto:support@casualgaming.no"
      label = "Brukerstøtte"

    [[params.footer.social]]
      icon = "fas fa-envelope"
      url = "mailto:post@casualgaming.no"
      label = "Kontakt"

    [[params.footer.line]]
      text = "Orgnr. [993 396 605](https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=993396605)"

    [[params.footer.line]]
      text = "[cag-web-2](https://github.com/CasualGaming/cag-web-2)"

    [[params.footer.line]]
      text = "Drevet av [Hugo](https://gohugo.io/) med temaet [Fifty](https://github.com/CasualGaming/fifty)"
