# Site settings
# Needs to be an absolute prefix
baseURL = "/"
languageCode = "en-us"
title = "Casual Gaming "
theme = "fifty"
publishDir = "public"
enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Casual Gaming"
  description = "For spillinteresserte i Trondheim"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # 404 error customization
  [params.error404]
    heading = "Siden kunne ikke finnes"
    text = "Vennligst [gå hjem](/)."

  # Navigation Section
  [params.navigation]
    logo = "logo-text.png"
    menu = "Meny"

    [[params.navigation.links]]
      name = "Hjem"
      url = "/"

    [[params.navigation.links]]
      name = "Om oss"
      url = "/om"

    [[params.navigation.links]]
      name = "TrøndeLAN"
      url = "/trondelan"

    [[params.navigation.links]]
      name = "StudLAN"
      url = "/studlan"

    [[params.navigation.links]]
      name = "Spillkvelder"
      url = "/spillkvelder"

    [[params.navigation.links]]
      name = "For bedrifter"
      url = "/for-bedrifter"

    [[params.navigation.links]]
      name = "Crew-opptak"
      url = "/opptak"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    image = "/img/logo-text.png"
    subtitle = "For spillinteresserte i Trondheim"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "TrøndeLAN"
      subtitle = "Et LAN-party for alle"
      image = "home/trondelan.jpg"
      url = "/trondelan"

    [[params.tiles.showcase]]
      title = "StudLAN"
      subtitle = "Et tradisjonsrikt LAN-party for studenter"
      image = "home/studlan.jpg"
      url = "/studlan"

    [[params.tiles.showcase]]
      title = "Spillkvelder"
      subtitle = "Sosialt og gøy"
      image = "home/konsoll_brett.jpg"
      url = "/spillkvelder"

    [[params.tiles.showcase]]
      title = "Crew-opptak"
      subtitle = "Bli med å arrangere"
      image = "home/bli_med.png"
      containImage = true
      url = "/opptak"

  # Section Type Two
  [params.two]
    enable = true
    title = "Casual Gaming"
    subtitle = """Casual Gaming er en ideell studentorganisasjon som har til formål
      å skape en felles sosial arena for spillinteresserte studenter og ungdom i Trondheimsområdet.
      Les mer om oss [her](/om)."""
    buttonText = "Følg oss på Facebook!"
    url = "https://www.facebook.com/CasualGamingTrondheim/"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Casual Gaming"

    # "fas" means FontAwesome solid, "fab" means FA brands

    [[params.footer.social]]
      icon = "fab fa-facebook"
      url= "https://www.facebook.com/CasualGamingTrondheim/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fab fa-instagram"
      url= "https://www.instagram.com/casualgamingno"
      label = "Instagram"

    [[params.footer.social]]
      icon = "fab fa-twitch"
      url= "https://www.twitch.tv/casualgamingnorway"
      label = "Twitch"

    [[params.footer.social]]
      icon = "fab fa-discord"
      url= "https://discord.gg/C7UDyte"
      label = "Discord"

    [[params.footer.social]]
      icon = "fab fa-github"
      url= "https://www.github.com/CasualGaming"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fas fa-envelope"
      url= "mailto:post@casualgaming.no"
      label = "E-Mail"

    [[params.footer.line]]
      text = "Orgnr. 993 396 605"

    [[params.footer.line]]
      text = "Drevet av [Hugo](https://gohugo.io/) med temaet [Fifty](https://github.com/CasualGaming/fifty)"
